collections:
  my_categories:
    output: true
    permalink: /category/:name/
  drafts:
    output: true
    permalink: /drafts/:title/

defaults:
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category

  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post

permalink: /:title/

name: busse.io
description: A collection of thoughts by Chris Busse
url: http://busse.io